import "./globals.css";
import type { Metadata } from "next";
import AuthSessionManager from "@/components/AuthSessionManager";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"font-sans antialiased"}
      >
      <main >
          <AuthSessionManager/>
          {children}
      </main>
      </body>
    </html>
  );
}
